---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-filesystem
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - <NAME OF INFRA NODE 1>
        - <NAME OF INFRA NODE 2>
        - <NAME OF INFRA NODE 3>
  storageClassDevices:
    - storageClassName: localfilesystem-sc
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
      - /dev/vdb
...
